# GitHub Actions workflow to generate a requirements.txt, for all the
# automatic processing that GitHub does, from a Poetry setup file, and
# commit the requirements.txt to the repo
#
# Author: lumbroso@cs.princeton.edu
# See GitHub documentation: https://git.io/JJL7O

name: "Update dependency file"

on:
  push:
    paths:
      - "pyproject.*"
      - "poetry.lock"

jobs:
  dependency-update:
    name: dependency-update
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --without-hashes > requirements.txt

      - name: Generate requirements-dev.txt
        run: poetry export --with dev -f requirements.txt --without-hashes > requirements-dev.txt

      - name: Commit generated requirements.txt
        uses: EndBug/add-and-commit@v9
        with:
          message: "Commit updated requirements for GH dependency graph + rtd.io"
          add: "requirements*.txt"
          cwd: "."
          force: true
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
