on: ["push", "pull_request"]

# Running tests with pytest in Python 3.8
name: pytest
jobs:
  pytest:
    name: pytest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run python -m pytest --cov=imslp --cov-branch tests/

      - name: Run codecov to upload report to site
        run: poetry run codecov -t ${{ secrets.CODECOV_TOKEN }}
